using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace NevermoreStudios.Gameplay
{
    [CreateAssetMenu(fileName = "GameplayTags", menuName = "Scriptable Objects/GameplayTags")]
    public class GameplayTags : ScriptableObject
    {
        public List<string> gameplayTags;
        private readonly Dictionary<string, int> _gameplayTagToId = new();
        private readonly List<string> _uniqueTags = new();
        private readonly Dictionary<int, int> _childToParentId = new();
        public static readonly int gameplayTagNotFoundCode = -2;

        private static GameplayTags _instance;
        public static GameplayTags Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = Resources.Load<GameplayTags>("GameplayTags");
                    _instance.ConstructGameplayTags();
                }
                return _instance;
            }
        }

        protected void ConstructGameplayTags()
        {
            foreach (string gameplayTag in gameplayTags)
            {
                string[] individualTags = gameplayTag.Split('.');
                string currentTag = "";

                for (int tagIndex = 0; tagIndex < individualTags.Length; tagIndex++)
                {                    
                    currentTag = (tagIndex == 0)
                        ? individualTags[tagIndex]
                        : $"{currentTag}.{individualTags[tagIndex]}"; //Appends to the string similar to +

                    if (!_gameplayTagToId.TryGetValue(currentTag, out var existingTag))
                    {
                        int newId = _uniqueTags.Count;
                        _gameplayTagToId[currentTag] = newId;
                        _uniqueTags.Add(currentTag);

                        if (tagIndex > 0)
                        {
                            string parentTag = string.Join(".", individualTags.Take(tagIndex));
                            _childToParentId[newId] = _gameplayTagToId[parentTag];
                        }
                        else
                        {
                            _childToParentId[newId] = -1; // root has no parent
                        }
                    }
                }
            }

            //TODO: Change this with its own gameplay tag settings
            // DeveloperSettings.GetInstanceAsync("DeveloperSettings").ContinueWith(t =>
            // {
            //     var devSettings = t.Result;
            //     if (devSettings.gameplayTagDevSettings.logTagCreation)
            //     {
            //         Debug.Log("GameplayTags are created:");
            //         foreach (string uniqueTag in _uniqueTags)
            //         {
            //             int tagId = _gameplayTagToId[uniqueTag];
            //             int parentTagId = _childToParentId[tagId];
            //             Debug.Log($"Tag: \"{uniqueTag}\" ID: {tagId} Parent ID: {parentTagId}");
            //         }
            //     }
            // });
        }

        public List<string> GetUniqueTags()
        {
            return _uniqueTags;
        }

        public int GetGameplayTagIDFromString(string gameplayTag)
        {
            return _gameplayTagToId.GetValueOrDefault(gameplayTag, gameplayTagNotFoundCode);
        }

        public int GetParentIdFromString(string gameplayTag)
        {
            int childId = _gameplayTagToId.GetValueOrDefault(gameplayTag, gameplayTagNotFoundCode);
            if (childId > -1)
            {
                return _childToParentId.GetValueOrDefault(childId, gameplayTagNotFoundCode);
            }
            return gameplayTagNotFoundCode;
        }

        public int GetParentIdFromId(int gameplayTag)
        {
            return _childToParentId.GetValueOrDefault(gameplayTag, gameplayTagNotFoundCode);
        }
        
#if UNITY_EDITOR
        private const string OutputPath = "Assets/Scripts/AutoGenerated/GameplayTagConsts.cs";

        public void GenerateConstClass()
        {
            if (gameplayTags == null || gameplayTags.Count == 0)
            {
                return;
            }

            GameplayTags gameplayTagsInstance = GameplayTags.Instance;
            gameplayTagsInstance.ConstructGameplayTags();
            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.");
            stringBuilder.AppendLine("namespace DiceSurvivors.AutoGenerated");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("    public static class GameplayTagConstants");
            stringBuilder.AppendLine("    {");

            foreach (var gameplayTag in _uniqueTags) //Also add parent tags as well
            {
                // "Gameplay.Request.SpawnMainProjectile" turns into safe Gameplay_Request_SpawnMainProjectile
                string safeName = gameplayTag.Replace(".", "_")
                    .Replace(" ", "_")
                    .Replace("-", "_");
                // Ensure identifier starts with a letter
                if (!char.IsLetter(safeName[0]))
                {
                    safeName = "_" + safeName;
                }

                stringBuilder.AppendLine($"        public const string {safeName} = \"{gameplayTag}\";");
                stringBuilder.AppendLine($"        public const int {safeName}_Id = {GetGameplayTagIDFromString(gameplayTag)};");
                stringBuilder.AppendLine($"        public const int {safeName}_Parent_Id = {GetParentIdFromString(gameplayTag)};");
                stringBuilder.AppendLine("");
            }

            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");

            // Ensure directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath));
            File.WriteAllText(OutputPath, stringBuilder.ToString());

            EditorApplication.delayCall += () =>
            {
                AssetDatabase.Refresh();
                Debug.Log($"GameplayTag Constants regenerated from {name}!");
            };
        }
#endif
    }
}
